### ISSUE TITLE
Tried arnheim2.ipynb - See Error

### ISSUE THREAD

**Issue by metaphorz** [deepmind/arnheim#2]
Cell "Preliminaries" works fine in Colab. The next cell throws an error: 

`Torch version: 1.9.0+cu111

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-4-f548071b3262> in <module>()
     18 
     19 import clip
---> 20 import pydiffvg
     21 
     22 os.environ["FFMPEG_BINARY"] = "ffmpeg"

2 frames

/content/diffvg/pydiffvg/render_pytorch.py in RenderFunction()
     25                         shapes,
     26                         shape_groups,
---> 27                         filter = pydiffvg.PixelFilter(type = diffvg.FilterType.box,
     28                                                       radius = torch.tensor(0.5)),
     29                         output_type = OutputType.color,

AttributeError: module 'diffvg' has no attribute 'FilterType' `

Never mind. Can close. I didn't see step 4. Best if you can get the user to click on a button to restart run time in the cell flow.

**Comment by dylski** [comment]
Will look into improving the error when the user forgets to follow step 4
