### ISSUE TITLE
This isn't going to work in a local windows runtime, huh??

### ISSUE THREAD

**Issue by exitrip** [deepmind/arnheim#3]
First fail is building diffvg.  I'll see about installing CMake, but tell me if it's hopeless if you can please.

**Comment by exitrip** [comment]
An excerpt of `pip freeze` shows that cmake does install some sort of (py)diffvg after much coercing, but, no matter how much I restart the jupyter runtime, it still fails to actually bind : `
AttributeError: module 'diffvg' has no attribute 'FilterType'`

```
....
decorator==4.4.2
defusedxml==0.6.0
diffvg==0.0.1
entrypoints==0.3
ftfy==6.0.3
...
```

... I'm mostly just leaving breadcrumbs on the internet, but any help would be appreciated.

**Comment by dylski** [comment]
Alas, I have no experience trying to get this working with jupyter or on Windows.
