### ISSUE TITLE
CLIPDraw license

### ISSUE THREAD

**Issue by Aspie96** [deepmind/arnheim#5]
The README says:
> CLIPDraw provided under license, Copyright 2021 Kevin Frans.

I am slightly confused as to what this means.

Can arnheim_2.ipynb be used under the terms of the Apache 2.0 license? Is CLIPDraw provided under the Apache 2.0 license?

**Comment by dylski** [comment]
Yes, all the code in this this repo can be used under the terms of the Apache 2.0 license.
CLIPDraw has also been licensed under Apache 2.0, although the license has only just been updated on the repo https://github.com/kvfrans/clipdraw/ so I can understand your confusion.

**Comment by Aspie96** [comment]
Thank you @dylski.
I was about to comment on the recent licensing of clipdraw. You beat me at it.

"Provided under license" still a bit unclear IMHO. It would probably be better to mention the Apache 2.0 license in that notice (or not mention licensing of ClipDRAW at all, since now there is no confusion) and link to the ClipDRAW repo.
